### ISSUE TITLE
Sender Update by ID and update Email issues

### ISSUE THREAD

**Issue by ODGithub** [mailjet/mailjet-apiv3-java#33]
1) When i try to update the Email of a sender object, i get "Error '400' - One or more arguments are missing or maybe mispelling. Details: Not allowed to change email address - "
However in the documentation, in Update, the attribute is Mandatory and not ReadOnly.

2) Same as Metasender issue: 
When i try to Update a Sender by its ID, i get something like the following message but always maximum expected 1but it gets multiple objects:
"RETURNS: Error '-5' - The MailJet API Client is incorrectly used. Details: Returned object by MailJet API are more than expected. Maximum expected: 1; Returned: 4."
When i try to Update by Email i get the correct results.
Note: Viewing by ID returns a single result and not multiple.

**Comment by GuillaumeBadi** [comment]
Hey! :airplane: 

We released a new version for this wrapper. It's a lighter/simpler version of the old one. Check it out:
https://github.com/mailjet/mailjet-apiv3-java/tree/v3.0.0

Our doc is also up to date with this wrapper: http://dev.mailjet.com/guides/?java

**Comment by ODGithub** [comment]
Yes , thank you for the update, but you still do not answer to any of the issues here, especially mine. 
I have tried you whole API , maybe the only one who has done so, and i am getting ignored.
